version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pessoa_crud
    networks:
      - bubble
  pessoa:
    container_name: pessoa
    depends_on:
      - mysql
    build: .
    networks:
      - bubble
networks:
  bubble:
    external: true