spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pessoa_crud
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
